/**
 * Global city catalog — Numbeo COL index (excl. rent), New York = 100 baseline.
 * Approximate values for directional comparison; refresh from Numbeo periodically.
 *
 * @typedef {import("./data.js").City} City
 */

/** @type {Omit<City, "country"> & { country: string }[]} */
export const CITY_CATALOG = [
  // —— Europe ——
  { id: "copenhagen", name: "Copenhagen", country: "Denmark", countryCode: "dk", numbeoColIndex: 83.2, currencyCode: "DKK", currencyLabel: "kr." },
  { id: "london", name: "London", country: "United Kingdom", countryCode: "gb", numbeoColIndex: 87.2, currencyCode: "GBP", currencyLabel: "£" },
  { id: "zurich", name: "Zurich", country: "Switzerland", countryCode: "ch", numbeoColIndex: 122.4, currencyCode: "CHF", currencyLabel: "CHF" },
  { id: "geneva", name: "Geneva", country: "Switzerland", countryCode: "ch", numbeoColIndex: 114.7, currencyCode: "CHF", currencyLabel: "CHF" },
  { id: "basel", name: "Basel", country: "Switzerland", countryCode: "ch", numbeoColIndex: 114.2, currencyCode: "CHF", currencyLabel: "CHF" },
  { id: "oslo", name: "Oslo", country: "Norway", countryCode: "no", numbeoColIndex: 96.1, currencyCode: "NOK", currencyLabel: "kr" },
  { id: "paris", name: "Paris", country: "France", countryCode: "fr", numbeoColIndex: 77.4, currencyCode: "EUR", currencyLabel: "€" },
  { id: "lyon", name: "Lyon", country: "France", countryCode: "fr", numbeoColIndex: 71.6, currencyCode: "EUR", currencyLabel: "€" },
  { id: "marseille", name: "Marseille", country: "France", countryCode: "fr", numbeoColIndex: 72.8, currencyCode: "EUR", currencyLabel: "€" },
  { id: "dublin", name: "Dublin", country: "Ireland", countryCode: "ie", numbeoColIndex: 75.0, currencyCode: "EUR", currencyLabel: "€" },
  { id: "amsterdam", name: "Amsterdam", country: "Netherlands", countryCode: "nl", numbeoColIndex: 80.6, currencyCode: "EUR", currencyLabel: "€" },
  { id: "rotterdam", name: "Rotterdam", country: "Netherlands", countryCode: "nl", numbeoColIndex: 73.1, currencyCode: "EUR", currencyLabel: "€" },
  { id: "brussels", name: "Brussels", country: "Belgium", countryCode: "be", numbeoColIndex: 69.7, currencyCode: "EUR", currencyLabel: "€" },
  { id: "luxembourg", name: "Luxembourg", country: "Luxembourg", countryCode: "lu", numbeoColIndex: 78.6, currencyCode: "EUR", currencyLabel: "€" },
  { id: "stockholm", name: "Stockholm", country: "Sweden", countryCode: "se", numbeoColIndex: 79.9, currencyCode: "SEK", currencyLabel: "kr" },
  { id: "gothenburg", name: "Gothenburg", country: "Sweden", countryCode: "se", numbeoColIndex: 65.5, currencyCode: "SEK", currencyLabel: "kr" },
  { id: "helsinki", name: "Helsinki", country: "Finland", countryCode: "fi", numbeoColIndex: 73.1, currencyCode: "EUR", currencyLabel: "€" },
  { id: "berlin", name: "Berlin", country: "Germany", countryCode: "de", numbeoColIndex: 70.1, currencyCode: "EUR", currencyLabel: "€" },
  { id: "munich", name: "Munich", country: "Germany", countryCode: "de", numbeoColIndex: 76.5, currencyCode: "EUR", currencyLabel: "€" },
  { id: "frankfurt", name: "Frankfurt", country: "Germany", countryCode: "de", numbeoColIndex: 70.9, currencyCode: "EUR", currencyLabel: "€" },
  { id: "hamburg", name: "Hamburg", country: "Germany", countryCode: "de", numbeoColIndex: 70.8, currencyCode: "EUR", currencyLabel: "€" },
  { id: "vienna", name: "Vienna", country: "Austria", countryCode: "at", numbeoColIndex: 74.7, currencyCode: "EUR", currencyLabel: "€" },
  { id: "milan", name: "Milan", country: "Italy", countryCode: "it", numbeoColIndex: 73.1, currencyCode: "EUR", currencyLabel: "€" },
  { id: "rome", name: "Rome", country: "Italy", countryCode: "it", numbeoColIndex: 59.4, currencyCode: "EUR", currencyLabel: "€" },
  { id: "naples", name: "Naples", country: "Italy", countryCode: "it", numbeoColIndex: 58.9, currencyCode: "EUR", currencyLabel: "€" },
  { id: "barcelona", name: "Barcelona", country: "Spain", countryCode: "es", numbeoColIndex: 59.9, currencyCode: "EUR", currencyLabel: "€" },
  { id: "madrid", name: "Madrid", country: "Spain", countryCode: "es", numbeoColIndex: 58.6, currencyCode: "EUR", currencyLabel: "€" },
  { id: "valencia", name: "Valencia", country: "Spain", countryCode: "es", numbeoColIndex: 50.9, currencyCode: "EUR", currencyLabel: "€" },
  { id: "lisbon", name: "Lisbon", country: "Portugal", countryCode: "pt", numbeoColIndex: 54.1, currencyCode: "EUR", currencyLabel: "€" },
  { id: "porto", name: "Porto", country: "Portugal", countryCode: "pt", numbeoColIndex: 50.1, currencyCode: "EUR", currencyLabel: "€" },
  { id: "prague", name: "Prague", country: "Czech Republic", countryCode: "cz", numbeoColIndex: 57.6, currencyCode: "CZK", currencyLabel: "Kč" },
  { id: "warsaw", name: "Warsaw", country: "Poland", countryCode: "pl", numbeoColIndex: 52.3, currencyCode: "PLN", currencyLabel: "zł" },
  { id: "krakow", name: "Kraków", country: "Poland", countryCode: "pl", numbeoColIndex: 50.0, currencyCode: "PLN", currencyLabel: "zł" },
  { id: "budapest", name: "Budapest", country: "Hungary", countryCode: "hu", numbeoColIndex: 54.0, currencyCode: "HUF", currencyLabel: "Ft" },
  { id: "bucharest", name: "Bucharest", country: "Romania", countryCode: "ro", numbeoColIndex: 44.3, currencyCode: "RON", currencyLabel: "lei" },
  { id: "sofia", name: "Sofia", country: "Bulgaria", countryCode: "bg", numbeoColIndex: 48.8, currencyCode: "BGN", currencyLabel: "лв" },
  { id: "athens", name: "Athens", country: "Greece", countryCode: "gr", numbeoColIndex: 56.0, currencyCode: "EUR", currencyLabel: "€" },
  { id: "istanbul", name: "Istanbul", country: "Turkey", countryCode: "tr", numbeoColIndex: 45.5, currencyCode: "TRY", currencyLabel: "₺" },
  { id: "ankara", name: "Ankara", country: "Turkey", countryCode: "tr", numbeoColIndex: 40.9, currencyCode: "TRY", currencyLabel: "₺" },
  { id: "kyiv", name: "Kyiv", country: "Ukraine", countryCode: "ua", numbeoColIndex: 31.9, currencyCode: "UAH", currencyLabel: "₴" },
  { id: "riga", name: "Riga", country: "Latvia", countryCode: "lv", numbeoColIndex: 54.0, currencyCode: "EUR", currencyLabel: "€" },
  { id: "tallinn", name: "Tallinn", country: "Estonia", countryCode: "ee", numbeoColIndex: 63.3, currencyCode: "EUR", currencyLabel: "€" },
  { id: "vilnius", name: "Vilnius", country: "Lithuania", countryCode: "lt", numbeoColIndex: 51.6, currencyCode: "EUR", currencyLabel: "€" },
  { id: "zagreb", name: "Zagreb", country: "Croatia", countryCode: "hr", numbeoColIndex: 52.8, currencyCode: "EUR", currencyLabel: "€" },
  { id: "belgrade", name: "Belgrade", country: "Serbia", countryCode: "rs", numbeoColIndex: 47.8, currencyCode: "RSD", currencyLabel: "RSD" },
  { id: "manchester", name: "Manchester", country: "United Kingdom", countryCode: "gb", numbeoColIndex: 66.8, currencyCode: "GBP", currencyLabel: "£" },
  { id: "edinburgh", name: "Edinburgh", country: "United Kingdom", countryCode: "gb", numbeoColIndex: 71.9, currencyCode: "GBP", currencyLabel: "£" },
  { id: "reykjavik", name: "Reykjavik", country: "Iceland", countryCode: "is", numbeoColIndex: 99.3, currencyCode: "ISK", currencyLabel: "kr" },
  { id: "birmingham", name: "Birmingham", country: "United Kingdom", countryCode: "gb", numbeoColIndex: 69.1, currencyCode: "GBP", currencyLabel: "£" },
  { id: "glasgow", name: "Glasgow", country: "United Kingdom", countryCode: "gb", numbeoColIndex: 67.8, currencyCode: "GBP", currencyLabel: "£" },
  { id: "nice", name: "Nice", country: "France", countryCode: "fr", numbeoColIndex: 73.6, currencyCode: "EUR", currencyLabel: "€" },
  { id: "cologne", name: "Cologne", country: "Germany", countryCode: "de", numbeoColIndex: 70.4, currencyCode: "EUR", currencyLabel: "€" },
  { id: "stuttgart", name: "Stuttgart", country: "Germany", countryCode: "de", numbeoColIndex: 69.1, currencyCode: "EUR", currencyLabel: "€" },
  { id: "florence", name: "Florence", country: "Italy", countryCode: "it", numbeoColIndex: 68.9, currencyCode: "EUR", currencyLabel: "€" },
  { id: "seville", name: "Seville", country: "Spain", countryCode: "es", numbeoColIndex: 47.9, currencyCode: "EUR", currencyLabel: "€" },
  { id: "antwerp", name: "Antwerp", country: "Belgium", countryCode: "be", numbeoColIndex: 71.0, currencyCode: "EUR", currencyLabel: "€" },
  { id: "cork", name: "Cork", country: "Ireland", countryCode: "ie", numbeoColIndex: 71.7, currencyCode: "EUR", currencyLabel: "€" },
  { id: "valletta", name: "Valletta", country: "Malta", countryCode: "mt", numbeoColIndex: 62.5, currencyCode: "EUR", currencyLabel: "€" },
  { id: "nicosia", name: "Nicosia", country: "Cyprus", countryCode: "cy", numbeoColIndex: 57.1, currencyCode: "EUR", currencyLabel: "€" },
  { id: "bratislava", name: "Bratislava", country: "Slovakia", countryCode: "sk", numbeoColIndex: 55.6, currencyCode: "EUR", currencyLabel: "€" },
  { id: "ljubljana", name: "Ljubljana", country: "Slovenia", countryCode: "si", numbeoColIndex: 56.6, currencyCode: "EUR", currencyLabel: "€" },
  { id: "thessaloniki", name: "Thessaloniki", country: "Greece", countryCode: "gr", numbeoColIndex: 54.4, currencyCode: "EUR", currencyLabel: "€" },
  { id: "antalya", name: "Antalya", country: "Turkey", countryCode: "tr", numbeoColIndex: 39.0, currencyCode: "TRY", currencyLabel: "₺" },
  { id: "poznan", name: "Poznań", country: "Poland", countryCode: "pl", numbeoColIndex: 46.5, currencyCode: "PLN", currencyLabel: "zł" },
  { id: "split", name: "Split", country: "Croatia", countryCode: "hr", numbeoColIndex: 56.6, currencyCode: "EUR", currencyLabel: "€" },
  { id: "sarajevo", name: "Sarajevo", country: "Bosnia and Herzegovina", countryCode: "ba", numbeoColIndex: 43.3, currencyCode: "BAM", currencyLabel: "KM" },
  { id: "skopje", name: "Skopje", country: "North Macedonia", countryCode: "mk", numbeoColIndex: 37.5, currencyCode: "MKD", currencyLabel: "MKD" },

  // —— Americas ——
  { id: "new-york", name: "New York", country: "United States", countryCode: "us", numbeoColIndex: 100.0, currencyCode: "USD", currencyLabel: "$" },
  { id: "san-francisco", name: "San Francisco", country: "United States", countryCode: "us", numbeoColIndex: 94.9, currencyCode: "USD", currencyLabel: "$" },
  { id: "los-angeles", name: "Los Angeles", country: "United States", countryCode: "us", numbeoColIndex: 81.7, currencyCode: "USD", currencyLabel: "$" },
  { id: "chicago", name: "Chicago", country: "United States", countryCode: "us", numbeoColIndex: 73.2, currencyCode: "USD", currencyLabel: "$" },
  { id: "boston", name: "Boston", country: "United States", countryCode: "us", numbeoColIndex: 86.2, currencyCode: "USD", currencyLabel: "$" },
  { id: "washington-dc", name: "Washington DC", country: "United States", countryCode: "us", numbeoColIndex: 88.9, currencyCode: "USD", currencyLabel: "$" },
  { id: "seattle", name: "Seattle", country: "United States", countryCode: "us", numbeoColIndex: 89.0, currencyCode: "USD", currencyLabel: "$" },
  { id: "miami", name: "Miami", country: "United States", countryCode: "us", numbeoColIndex: 83.7, currencyCode: "USD", currencyLabel: "$" },
  { id: "austin", name: "Austin", country: "United States", countryCode: "us", numbeoColIndex: 69.6, currencyCode: "USD", currencyLabel: "$" },
  { id: "denver", name: "Denver", country: "United States", countryCode: "us", numbeoColIndex: 76.5, currencyCode: "USD", currencyLabel: "$" },
  { id: "houston", name: "Houston", country: "United States", countryCode: "us", numbeoColIndex: 63.2, currencyCode: "USD", currencyLabel: "$" },
  { id: "toronto", name: "Toronto", country: "Canada", countryCode: "ca", numbeoColIndex: 65.6, currencyCode: "CAD", currencyLabel: "C$" },
  { id: "vancouver", name: "Vancouver", country: "Canada", countryCode: "ca", numbeoColIndex: 66.7, currencyCode: "CAD", currencyLabel: "C$" },
  { id: "montreal", name: "Montreal", country: "Canada", countryCode: "ca", numbeoColIndex: 59.4, currencyCode: "CAD", currencyLabel: "C$" },
  { id: "calgary", name: "Calgary", country: "Canada", countryCode: "ca", numbeoColIndex: 62.7, currencyCode: "CAD", currencyLabel: "C$" },
  { id: "mexico-city", name: "Mexico City", country: "Mexico", countryCode: "mx", numbeoColIndex: 48.0, currencyCode: "MXN", currencyLabel: "MX$" },
  { id: "guadalajara", name: "Guadalajara", country: "Mexico", countryCode: "mx", numbeoColIndex: 42.7, currencyCode: "MXN", currencyLabel: "MX$" },
  { id: "sao-paulo", name: "São Paulo", country: "Brazil", countryCode: "br", numbeoColIndex: 41.3, currencyCode: "BRL", currencyLabel: "R$" },
  { id: "rio-de-janeiro", name: "Rio de Janeiro", country: "Brazil", countryCode: "br", numbeoColIndex: 35.8, currencyCode: "BRL", currencyLabel: "R$" },
  { id: "buenos-aires", name: "Buenos Aires", country: "Argentina", countryCode: "ar", numbeoColIndex: 50.7, currencyCode: "ARS", currencyLabel: "ARS" },
  { id: "santiago", name: "Santiago", country: "Chile", countryCode: "cl", numbeoColIndex: 42.4, currencyCode: "CLP", currencyLabel: "CLP" },
  { id: "lima", name: "Lima", country: "Peru", countryCode: "pe", numbeoColIndex: 34.8, currencyCode: "PEN", currencyLabel: "S/" },
  { id: "bogota", name: "Bogotá", country: "Colombia", countryCode: "co", numbeoColIndex: 34.7, currencyCode: "COP", currencyLabel: "COP" },
  { id: "panama-city", name: "Panama City", country: "Panama", countryCode: "pa", numbeoColIndex: 47.6, currencyCode: "USD", currencyLabel: "$" },
  { id: "philadelphia", name: "Philadelphia", country: "United States", countryCode: "us", numbeoColIndex: 78.8, currencyCode: "USD", currencyLabel: "$" },
  { id: "atlanta", name: "Atlanta", country: "United States", countryCode: "us", numbeoColIndex: 76.0, currencyCode: "USD", currencyLabel: "$" },
  { id: "san-diego", name: "San Diego", country: "United States", countryCode: "us", numbeoColIndex: 80.0, currencyCode: "USD", currencyLabel: "$" },
  { id: "portland", name: "Portland", country: "United States", countryCode: "us", numbeoColIndex: 80.0, currencyCode: "USD", currencyLabel: "$" },
  { id: "las-vegas", name: "Las Vegas", country: "United States", countryCode: "us", numbeoColIndex: 68.9, currencyCode: "USD", currencyLabel: "$" },
  { id: "honolulu", name: "Honolulu", country: "United States", countryCode: "us", numbeoColIndex: 101.8, currencyCode: "USD", currencyLabel: "$" },
  { id: "ottawa", name: "Ottawa", country: "Canada", countryCode: "ca", numbeoColIndex: 61.5, currencyCode: "CAD", currencyLabel: "C$" },
  { id: "quebec-city", name: "Quebec City", country: "Canada", countryCode: "ca", numbeoColIndex: 58.9, currencyCode: "CAD", currencyLabel: "C$" },
  { id: "cancun", name: "Cancún", country: "Mexico", countryCode: "mx", numbeoColIndex: 48.0, currencyCode: "MXN", currencyLabel: "MX$" },
  { id: "monterrey", name: "Monterrey", country: "Mexico", countryCode: "mx", numbeoColIndex: 49.4, currencyCode: "MXN", currencyLabel: "MX$" },
  { id: "medellin", name: "Medellín", country: "Colombia", countryCode: "co", numbeoColIndex: 36.3, currencyCode: "COP", currencyLabel: "COP" },
  { id: "montevideo", name: "Montevideo", country: "Uruguay", countryCode: "uy", numbeoColIndex: 56.5, currencyCode: "UYU", currencyLabel: "$U" },
  { id: "quito", name: "Quito", country: "Ecuador", countryCode: "ec", numbeoColIndex: 33.6, currencyCode: "USD", currencyLabel: "$" },
  { id: "guayaquil", name: "Guayaquil", country: "Ecuador", countryCode: "ec", numbeoColIndex: 35.4, currencyCode: "USD", currencyLabel: "$" },
  { id: "san-jose-cr", name: "San José", country: "Costa Rica", countryCode: "cr", numbeoColIndex: 57.7, currencyCode: "CRC", currencyLabel: "₡" },
  { id: "santo-domingo", name: "Santo Domingo", country: "Dominican Republic", countryCode: "do", numbeoColIndex: 40.5, currencyCode: "DOP", currencyLabel: "RD$" },

  // —— Asia Pacific ——
  { id: "hong-kong", name: "Hong Kong", country: "Hong Kong", countryCode: "hk", numbeoColIndex: 73.8, currencyCode: "HKD", currencyLabel: "HK$" },
  { id: "singapore", name: "Singapore", country: "Singapore", countryCode: "sg", numbeoColIndex: 88.3, currencyCode: "SGD", currencyLabel: "S$" },
  { id: "tokyo", name: "Tokyo", country: "Japan", countryCode: "jp", numbeoColIndex: 53.8, currencyCode: "JPY", currencyLabel: "¥" },
  { id: "osaka", name: "Osaka", country: "Japan", countryCode: "jp", numbeoColIndex: 42.3, currencyCode: "JPY", currencyLabel: "¥" },
  { id: "seoul", name: "Seoul", country: "South Korea", countryCode: "kr", numbeoColIndex: 60.8, currencyCode: "KRW", currencyLabel: "₩" },
  { id: "busan", name: "Busan", country: "South Korea", countryCode: "kr", numbeoColIndex: 46.9, currencyCode: "KRW", currencyLabel: "₩" },
  { id: "taipei", name: "Taipei", country: "Taiwan", countryCode: "tw", numbeoColIndex: 54.1, currencyCode: "TWD", currencyLabel: "NT$" },
  { id: "shanghai", name: "Shanghai", country: "China", countryCode: "cn", numbeoColIndex: 39.1, currencyCode: "CNY", currencyLabel: "¥" },
  { id: "beijing", name: "Beijing", country: "China", countryCode: "cn", numbeoColIndex: 37.3, currencyCode: "CNY", currencyLabel: "¥" },
  { id: "shenzhen", name: "Shenzhen", country: "China", countryCode: "cn", numbeoColIndex: 37.5, currencyCode: "CNY", currencyLabel: "¥" },
  { id: "guangzhou", name: "Guangzhou", country: "China", countryCode: "cn", numbeoColIndex: 35.4, currencyCode: "CNY", currencyLabel: "¥" },
  { id: "chengdu", name: "Chengdu", country: "China", countryCode: "cn", numbeoColIndex: 27.8, currencyCode: "CNY", currencyLabel: "¥" },
  { id: "mumbai", name: "Mumbai", country: "India", countryCode: "in", numbeoColIndex: 24.6, currencyCode: "INR", currencyLabel: "₹" },
  { id: "delhi", name: "Delhi", country: "India", countryCode: "in", numbeoColIndex: 21.1, currencyCode: "INR", currencyLabel: "₹" },
  { id: "bangalore", name: "Bangalore", country: "India", countryCode: "in", numbeoColIndex: 20.6, currencyCode: "INR", currencyLabel: "₹" },
  { id: "chennai", name: "Chennai", country: "India", countryCode: "in", numbeoColIndex: 19.0, currencyCode: "INR", currencyLabel: "₹" },
  { id: "hyderabad", name: "Hyderabad", country: "India", countryCode: "in", numbeoColIndex: 20.5, currencyCode: "INR", currencyLabel: "₹" },
  { id: "bangkok", name: "Bangkok", country: "Thailand", countryCode: "th", numbeoColIndex: 41.1, currencyCode: "THB", currencyLabel: "฿" },
  { id: "kuala-lumpur", name: "Kuala Lumpur", country: "Malaysia", countryCode: "my", numbeoColIndex: 38.5, currencyCode: "MYR", currencyLabel: "RM" },
  { id: "jakarta", name: "Jakarta", country: "Indonesia", countryCode: "id", numbeoColIndex: 28.1, currencyCode: "IDR", currencyLabel: "Rp" },
  { id: "bali", name: "Bali", country: "Indonesia", countryCode: "id", numbeoColIndex: 33.5, currencyCode: "IDR", currencyLabel: "Rp" },
  { id: "manila", name: "Manila", country: "Philippines", countryCode: "ph", numbeoColIndex: 33.2, currencyCode: "PHP", currencyLabel: "₱" },
  { id: "ho-chi-minh-city", name: "Ho Chi Minh City", country: "Vietnam", countryCode: "vn", numbeoColIndex: 28.1, currencyCode: "VND", currencyLabel: "₫" },
  { id: "hanoi", name: "Hanoi", country: "Vietnam", countryCode: "vn", numbeoColIndex: 27.7, currencyCode: "VND", currencyLabel: "₫" },
  { id: "sydney", name: "Sydney", country: "Australia", countryCode: "au", numbeoColIndex: 77.3, currencyCode: "AUD", currencyLabel: "A$" },
  { id: "melbourne", name: "Melbourne", country: "Australia", countryCode: "au", numbeoColIndex: 76.1, currencyCode: "AUD", currencyLabel: "A$" },
  { id: "brisbane", name: "Brisbane", country: "Australia", countryCode: "au", numbeoColIndex: 68.9, currencyCode: "AUD", currencyLabel: "A$" },
  { id: "perth", name: "Perth", country: "Australia", countryCode: "au", numbeoColIndex: 72.7, currencyCode: "AUD", currencyLabel: "A$" },
  { id: "auckland", name: "Auckland", country: "New Zealand", countryCode: "nz", numbeoColIndex: 64.9, currencyCode: "NZD", currencyLabel: "NZ$" },
  { id: "wellington", name: "Wellington", country: "New Zealand", countryCode: "nz", numbeoColIndex: 65.0, currencyCode: "NZD", currencyLabel: "NZ$" },
  { id: "kyoto", name: "Kyoto", country: "Japan", countryCode: "jp", numbeoColIndex: 51.7, currencyCode: "JPY", currencyLabel: "¥" },
  { id: "nagoya", name: "Nagoya", country: "Japan", countryCode: "jp", numbeoColIndex: 49.7, currencyCode: "JPY", currencyLabel: "¥" },
  { id: "chiang-mai", name: "Chiang Mai", country: "Thailand", countryCode: "th", numbeoColIndex: 32.1, currencyCode: "THB", currencyLabel: "฿" },
  { id: "phuket", name: "Phuket", country: "Thailand", countryCode: "th", numbeoColIndex: 40.8, currencyCode: "THB", currencyLabel: "฿" },
  { id: "da-nang", name: "Da Nang", country: "Vietnam", countryCode: "vn", numbeoColIndex: 26.3, currencyCode: "VND", currencyLabel: "₫" },
  { id: "colombo", name: "Colombo", country: "Sri Lanka", countryCode: "lk", numbeoColIndex: 32.7, currencyCode: "LKR", currencyLabel: "Rs" },
  { id: "karachi", name: "Karachi", country: "Pakistan", countryCode: "pk", numbeoColIndex: 21.2, currencyCode: "PKR", currencyLabel: "₨" },
  { id: "lahore", name: "Lahore", country: "Pakistan", countryCode: "pk", numbeoColIndex: 20.8, currencyCode: "PKR", currencyLabel: "₨" },
  { id: "islamabad", name: "Islamabad", country: "Pakistan", countryCode: "pk", numbeoColIndex: 24.0, currencyCode: "PKR", currencyLabel: "₨" },
  { id: "pune", name: "Pune", country: "India", countryCode: "in", numbeoColIndex: 21.4, currencyCode: "INR", currencyLabel: "₹" },
  { id: "kolkata", name: "Kolkata", country: "India", countryCode: "in", numbeoColIndex: 18.5, currencyCode: "INR", currencyLabel: "₹" },
  { id: "macau", name: "Macau", country: "Macau", countryCode: "mo", numbeoColIndex: 48.3, currencyCode: "HKD", currencyLabel: "HK$" },
  { id: "hangzhou", name: "Hangzhou", country: "China", countryCode: "cn", numbeoColIndex: 35.0, currencyCode: "CNY", currencyLabel: "¥" },
  { id: "phnom-penh", name: "Phnom Penh", country: "Cambodia", countryCode: "kh", numbeoColIndex: 36.3, currencyCode: "KHR", currencyLabel: "៛" },
  { id: "yangon", name: "Yangon", country: "Myanmar", countryCode: "mm", numbeoColIndex: 20.7, currencyCode: "MMK", currencyLabel: "K" },
  { id: "kathmandu", name: "Kathmandu", country: "Nepal", countryCode: "np", numbeoColIndex: 22.7, currencyCode: "NPR", currencyLabel: "₨" },
  { id: "dhaka", name: "Dhaka", country: "Bangladesh", countryCode: "bd", numbeoColIndex: 25.3, currencyCode: "BDT", currencyLabel: "৳" },
  { id: "jeju", name: "Jeju", country: "South Korea", countryCode: "kr", numbeoColIndex: 44.8, currencyCode: "KRW", currencyLabel: "₩" },
  { id: "christchurch", name: "Christchurch", country: "New Zealand", countryCode: "nz", numbeoColIndex: 58.5, currencyCode: "NZD", currencyLabel: "NZ$" },
  { id: "adelaide", name: "Adelaide", country: "Australia", countryCode: "au", numbeoColIndex: 72.9, currencyCode: "AUD", currencyLabel: "A$" },
  { id: "canberra", name: "Canberra", country: "Australia", countryCode: "au", numbeoColIndex: 74.9, currencyCode: "AUD", currencyLabel: "A$" },
  { id: "queenstown", name: "Queenstown", country: "New Zealand", countryCode: "nz", numbeoColIndex: 49.7, currencyCode: "NZD", currencyLabel: "NZ$" },

  // —— Middle East & Africa ——
  { id: "dubai", name: "Dubai", country: "UAE", countryCode: "ae", numbeoColIndex: 61.7, currencyCode: "AED", currencyLabel: "AED" },
  { id: "abu-dhabi", name: "Abu Dhabi", country: "UAE", countryCode: "ae", numbeoColIndex: 52.7, currencyCode: "AED", currencyLabel: "AED" },
  { id: "doha", name: "Doha", country: "Qatar", countryCode: "qa", numbeoColIndex: 51.9, currencyCode: "QAR", currencyLabel: "QAR" },
  { id: "riyadh", name: "Riyadh", country: "Saudi Arabia", countryCode: "sa", numbeoColIndex: 48.0, currencyCode: "SAR", currencyLabel: "SAR" },
  { id: "jeddah", name: "Jeddah", country: "Saudi Arabia", countryCode: "sa", numbeoColIndex: 42.7, currencyCode: "SAR", currencyLabel: "SAR" },
  { id: "tel-aviv", name: "Tel Aviv", country: "Israel", countryCode: "il", numbeoColIndex: 101.5, currencyCode: "ILS", currencyLabel: "₪" },
  { id: "cairo", name: "Cairo", country: "Egypt", countryCode: "eg", numbeoColIndex: 21.9, currencyCode: "EGP", currencyLabel: "E£" },
  { id: "casablanca", name: "Casablanca", country: "Morocco", countryCode: "ma", numbeoColIndex: 34.2, currencyCode: "MAD", currencyLabel: "MAD" },
  { id: "marrakech", name: "Marrakech", country: "Morocco", countryCode: "ma", numbeoColIndex: 32.3, currencyCode: "MAD", currencyLabel: "MAD" },
  { id: "johannesburg", name: "Johannesburg", country: "South Africa", countryCode: "za", numbeoColIndex: 40.2, currencyCode: "ZAR", currencyLabel: "R" },
  { id: "cape-town", name: "Cape Town", country: "South Africa", countryCode: "za", numbeoColIndex: 39.8, currencyCode: "ZAR", currencyLabel: "R" },
  { id: "nairobi", name: "Nairobi", country: "Kenya", countryCode: "ke", numbeoColIndex: 32.0, currencyCode: "KES", currencyLabel: "KES" },
  { id: "lagos", name: "Lagos", country: "Nigeria", countryCode: "ng", numbeoColIndex: 25.8, currencyCode: "NGN", currencyLabel: "₦" },
  { id: "kuwait-city", name: "Kuwait City", country: "Kuwait", countryCode: "kw", numbeoColIndex: 45.1, currencyCode: "KWD", currencyLabel: "KD" },
  { id: "manama", name: "Manama", country: "Bahrain", countryCode: "bh", numbeoColIndex: 44.2, currencyCode: "BHD", currencyLabel: "BD" },
  { id: "muscat", name: "Muscat", country: "Oman", countryCode: "om", numbeoColIndex: 45.8, currencyCode: "OMR", currencyLabel: "OMR" },
  { id: "amman", name: "Amman", country: "Jordan", countryCode: "jo", numbeoColIndex: 43.4, currencyCode: "JOD", currencyLabel: "JOD" },
  { id: "beirut", name: "Beirut", country: "Lebanon", countryCode: "lb", numbeoColIndex: 52.1, currencyCode: "USD", currencyLabel: "$" },
  { id: "accra", name: "Accra", country: "Ghana", countryCode: "gh", numbeoColIndex: 40.9, currencyCode: "GHS", currencyLabel: "GH₵" },
  { id: "addis-ababa", name: "Addis Ababa", country: "Ethiopia", countryCode: "et", numbeoColIndex: 39.2, currencyCode: "ETB", currencyLabel: "Br" },
  { id: "tunis", name: "Tunis", country: "Tunisia", countryCode: "tn", numbeoColIndex: 30.3, currencyCode: "TND", currencyLabel: "DT" },
  { id: "durban", name: "Durban", country: "South Africa", countryCode: "za", numbeoColIndex: 34.5, currencyCode: "ZAR", currencyLabel: "R" },
  { id: "pretoria", name: "Pretoria", country: "South Africa", countryCode: "za", numbeoColIndex: 39.7, currencyCode: "ZAR", currencyLabel: "R" },
  { id: "dakar", name: "Dakar", country: "Senegal", countryCode: "sn", numbeoColIndex: 27.6, currencyCode: "XOF", currencyLabel: "CFA" },
];
